"""Generates a single self-contained script that runs the patched T9b recipe on a
Colab session, for `colab exec -f <output>`.

Why needed: `colab exec -f <file>` transmits ONLY that file's content (the remote has no
access to this machine's filesystem), and typer rejects any extra CLI args after it -- so
`colab exec -f recipe.py -- --config ...` fails with "unexpected extra argument". This
script therefore inlines the recipe source and hard-codes sys.argv inside it.

Usage:
    python3 tools/pod_setup/make_t9b_recipe_bundle.py --smoke   # Phase 1 (40 samples, 3 steps)
    python3 tools/pod_setup/make_t9b_recipe_bundle.py           # Phase-style full run
Output: /tmp/opencode/t9b_recipe_bundle.py  ->  colab exec -s <session> -f /tmp/opencode/t9b_recipe_bundle.py
"""

from __future__ import annotations

import argparse
import pathlib

RECIPE = (
    pathlib.Path(__file__).resolve().parents[2]
    / "external/meta_secalign/helpers/lora_dpo_single_device_t9b.py"
)
OUT = pathlib.Path("/tmp/opencode/t9b_recipe_bundle.py")

HEADER = '''\
# GENERATED by tools/pod_setup/make_t9b_recipe_bundle.py -- do not edit by hand.
import sys

sys.argv = ["lora_dpo_single_device_t9b.py", "--config", "/content/t9b.yaml"{extra_argv}]

'''

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--smoke", action="store_true",
                    help="prepend epochs=1, max_steps_per_epoch=3 to the recipe args")
    ap.add_argument("--config", default="/content/t9b.yaml")
    args = ap.parse_args()

    src = RECIPE.read_text(encoding="utf-8")
    guard = 'if __name__ == "__main__":\n    sys.exit(recipe_main())'
    assert guard in src, "recipe __main__ guard not found -- recipe file changed?"
    src = src.replace(guard, "")

    extra = ', "epochs=1", "max_steps_per_epoch=3"' if args.smoke else ""
    header = HEADER.replace("{extra_argv}", extra).replace("/content/t9b.yaml", args.config)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header + src + "\nsys.exit(recipe_main())\n", encoding="utf-8")
    print(f"[make_t9b_recipe_bundle] wrote {OUT} (smoke={args.smoke})")
